name: Java CI with Gradle

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: [self-hosted,Windows]
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
    
    - name: Set Environment Variables
      shell: powershell
      run: |
        $env:G_HOME = 'C:\Users\YAvanthika\Downloads\gradle-8.9-all\gradle-8.9'
        $env:JAVA_HOME = 'C:\Users\YAvanthika\AppData\Local\Programs\Eclipse Adoptium\jdk-17.0.11.9-hotspot'
        $env:PATH = "$env:G_HOME\bin;$env:JAVA_HOME\bin;$env:PATH"

    - name: Cache Gradle dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Check Gradle Version
      shell: powershell
      run: |
        $env:G_HOME = 'C:\Users\YAvanthika\Downloads\gradle-8.9-all\gradle-8.9'
        $env:JAVA_HOME = 'C:\Users\YAvanthika\AppData\Local\Programs\Eclipse Adoptium\jdk-17.0.11.9-hotspot'
        $env:PATH = "$env:G_HOME\bin;$env:JAVA_HOME\bin;$env:PATH"
        gradle --version

    - name: Build with Gradle
      shell: powershell
      run: |
        $env:G_HOME = 'C:\Users\YAvanthika\Downloads\gradle-8.9-all\gradle-8.9'
        $env:JAVA_HOME = 'C:\Users\YAvanthika\AppData\Local\Programs\Eclipse Adoptium\jdk-17.0.11.9-hotspot'
        $env:PATH = "$env:G_HOME\bin;$env:JAVA_HOME\bin;$env:PATH"
        ./gradlew build

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build-artifacts
        path: |
          build/libs
          build/reports
